### ISSUE TITLE
Bouton Login with Hilo ne fonctionne pas

### ISSUE THREAD

**Issue by jffortin** [SanterreJo/homebridge-hilo#55]
Après l'installation du plug-in, le bouton Login with Hilo ne fait absolument rien. J'utilise les plus récentes versions du plug-in (v2.0.1) et de Homebridge (v1.8.4). Ubuntu Noble (24.04.1 LTS) roule sur un Raspberry Pi 4 et est à jour.

```
[10/9/2024, 3:58:29 PM] [Homebridge UI] Running Command: /opt/homebridge/lib/node_modules/homebridge-config-ui-x/scripts/upgrade-install-plugin.sh homebridge-hilo 2.0.1 /var/lib/homebridge/node_modules
[10/9/2024, 3:58:35 PM] [Homebridge UI] [homebridge-hilo] node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8880
    at Server.setupListenHandle [as _listen2] (node:net:1904:16)
    at listenInCluster (node:net:1961:12)
    at Server.listen (node:net:2063:7)
    at Function.listen (/var/lib/homebridge/node_modules/homebridge-hilo/node_modules/express/lib/application.js:635:24)
    at new UiServer (/var/lib/homebridge/node_modules/homebridge-hilo/homebridge-ui/server.js:12:12)
    at /var/lib/homebridge/node_modules/homebridge-hilo/homebridge-ui/server.js:79:8
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-hilo/homebridge-ui/server.js:79:23)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1940:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 8880
}

Node.js v20.18.0
```

La plug-in Hilo a déjà fonctionné dans cette installation Homebridge, je l'ai réinstallé parce que je n'étais déjà plus capable de m'authentifier à Hilo en cliquant sur le bouton.

Je remarque qu'il bloque sur le port 8880, alors que rien ne roule sur ce port.

**Comment by jffortin** [comment]
Désolé;é, je réalise à l'instant que c'est similaire aux issues précédentes. J'utilise pourtant la version corrigée du plug-in. Si je peux être utile, juste me faire signe.

**Comment by SanterreJo** [comment]
Je crois que c'est différent des autres issues.

Dans ce cas-ci, c'est comme s'il y avait un autre process qui écoute sur le port 8880.

Ça pourrait être un process zombie du plugin lui-même.

As-tu essayé de redémarrer ton Raspberry Pi au complet, pas seulement homebridge?

**Comment by jffortin** [comment]
Bon, en fouillant un peu, j'ai fini par comprendre que le port 8880 était utilisé par un autre service. C'est donc un non-issue, désolé pour le dérangement. J'ai réussi à connecter Hilo à Homebridge en fermant le serveur UniFi. Je me demande toutefois si le plug-in a besoin en permanence du port 8880.

**Comment by SanterreJo** [comment]
Le plugin a besoin du port 8880 seulement pour le login. Donc une fois que tu as ton refresh token, tu peux redémarrer ton autre serveur sans problème.
