### ISSUE TITLE
Erreurs 401 après crash de Homebridge

### ISSUE THREAD

**Issue by y0m1g** [SanterreJo/homebridge-hilo#58]
Salut,
J'arrive à me logger correctement avec Hilo et a obtenir un refresh token, mais après plusieurs heures/jours le plugin retourne une erreur 401, et ce depuis plusieurs mois.
```
[11/11/2024, 8:52:57 AM] [Hilo] Error while fetching locations { statusCode: 401, message: 'Unauthorized' }
[11/11/2024, 8:52:57 AM] [Hilo] No locations found
```
Si je régénère un refresh token et redémarre Homebridge cela fonctionne à nouveau pour un bout, mais je finis toujours par retomber dans le même problème après un certain temps.

Je me disais que le problème devait venir de l'API d'Hilo, et que ça finirait par remarcher à l'automne quand plus de personnes utiliseraient à nouveau le service, mais rien ne semble avoir changé.
Je ne sais pas s'il y a vraiment quelque chose à faire du côté de ce plugin, mais je rapporte tout de même ce problème.

Est-ce possible que la connexion échoue si Homebridge crash et redémarre tout seul (cela m'arrive parfois)?

Je roule homebridge, Homebridge 1.9.5, Homebridge-UI 4.62.0, homebridge-hilo 2.0.1, sur Raspberry Pi 3.

**Comment by SanterreJo** [comment]
Je crois avoir identifié le problème, j'ai publié un correctif dans la version `v2.0.2--canary.bdc43bc.0`. Tiens-moi au courant si ça fonctionne, si tu as la chance de l'essayer.

**Comment by SanterreJo** [comment]
As-tu une idée combien de temps ça fonctionne avant d'avoir a recommencer le login flow?

**Comment by y0m1g** [comment]
C'est variable, ça m'est déjà arrivé que je doive me re-login 3 fois en 3 jours, mais généralement ça dure une bonne semaine ou plus.
Je me dis que c'est pas impossible que si mon RPi jam pendant plusieurs minutes (à cause d'updates par exemple?), et qu'ensuite mon Homebridge crash et reboot en conséquence, ça dépasse les 5min donc dans ce cas le refresh token expirerait car le plugin aurait pas eu la chance de le renouveler. 🤔

**Comment by y0m1g** [comment]
Aujourd'hui homebridge a reboot suite à une erreur du plugin SmartThings, et depuis le plugin Hilo a perdu la connexion:

> [11/19/2024, 6:42:14 AM] [Smartthings Plug (IK)] Failed to request status from Washer: Error: getaddrinfo EAI_AGAIN api.smartthings.com.  This is failure number 1
[11/19/2024, 6:42:14 AM] [Smartthings Plug (IK)] Poll failure on Washer
[11/19/2024, 6:42:17 AM] [Smartthings Plug (IK)] Failed to request status from Front door: Error: getaddrinfo EAI_AGAIN api.smartthings.com.  This is failure number 1
[11/19/2024, 6:42:17 AM] [Smartthings Plug (IK)] Poll failure on Front door
[11/19/2024, 6:42:17 AM] [Smartthings Plug (IK)] Poll failure on Front door
[11/19/2024, 6:42:17 AM] [Smartthings Plug (IK)] Poll failure on Front door
[11/19/2024, 6:42:20 AM] Error: HAP Status Error: -70402
    at new HapStatusError (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/hapStatusError.ts:17:10)
    at /usr/local/lib/node_modules/homebridge-smartthings-ik/src/services/lockService.ts:58:20
[11/19/2024, 6:42:22 AM] Got SIGTERM, shutting down Homebridge...
[...]
[11/19/2024, 6:43:00 AM] [Hilo] Initializing Hilo platform...
[11/19/2024, 6:43:00 AM] [Hilo] Initializing Hilo platform
[...]
[11/19/2024, 6:43:08 AM] Homebridge v1.8.5 (HAP v0.12.3) (Homebridge) is running on port 51826.
[...]
[11/19/2024, 6:43:09 AM] [Hilo] Unable to login undefined
[11/19/2024, 6:43:09 AM] [Hilo] You can try to refresh your login credentials by using the 'Login with Hilo' button in the plugin configuration in homebridge UI
[...]
[11/19/2024, 6:43:10 AM] [Hilo] Error while fetching locations { statusCode: 401, message: 'Unauthorized' }
[11/19/2024, 6:43:10 AM] [Hilo] No locations found

Je me demande si ce sont les reboots aléatoires la source du problème. Je vais continuer de monitorer les logs pour les prochaines fois.

**Comment by SanterreJo** [comment]
Est-ce que le plugin Hilo est configuré comme un child bridge? Ça pourrait peut-être aider à le rendre résilient au crash du plugin de smart things

**Comment by y0m1g** [comment]
Bonne idée! Je viens de passer le plugin SmartThings sur un child bridge, on va voir si ça stabilise mon Homebridge. 🤞

**Comment by SanterreJo** [comment]
C'est comme si lorsque le token est rafraichie, le nouveau token n'est pas remplacé dans la configuration (config.json), mais je n'arrive pas à reproduire.
